#!/bin/bash
set -e
execution_start=`date -R`

if [ -z $1 ]; then
   echo "no data source specified"
   exit 1
fi

data_source="$1"
period="$2"
periods="${3:-1}"


# tlp=${HOME}/Downloads/T-801/${data_source}
tlp=/tmp/snapshot/T-801/${data_source}
ldate=$(ls ${tlp} | sort -r | head -n 1)
for lpath in $(ls ${tlp}/${ldate}/ohlc | sort -r | egrep -v '(M|H|D)' | head -n ${periods}); do
   if [ ${period} != '5M' ]; then
      fpath=${tlp}/${ldate}/ohlc/${period}/${lpath}
   else
      fpath=${tlp}/${ldate}/ohlc/${lpath}
   fi
   echo ">> ${ldate} >> ${lpath} >> ${fpath}"

   bin/dit pod --dsource ${data_source} --period ${period} --fpath ${fpath}
done

execution_end=`date -R`
date -u -d @$(($(date -d "$execution_end" '+%s') - $(date -d "$execution_start" '+%s'))) '+%T'
